# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 1.0

install:
  - ruby --version
  - gem update --system --no-ri --no-rdoc
  - gem install bundler --no-document
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install -g grunt-cli
  - npm install

build: off
  
test_script:
  - node --version
  - npm --version
  - ps: npm test --no-color
  - cmd: npm test --no-color

after_test:
  - ps: npm run codeclimate --no-color
  - cmd: npm run codeclimate --no-color
